services:
  db:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo
      - MONGODB_INITDB_ROOT_PASSWORD=mongo
    ports:
      - '27017:27017'

volumes:
  mongo-data: